title: 'BitDevs SJ'
tagline: 'BitDevs is a community for those interested in discussing and participating in the research and development of Bitcoin and related protocols.'

menu:
  - {name: 'About BitDevs', url: '/about'}
  - {name: 'Events', url: '/events'}
  - {name: 'Meetup', url: 'https://www.meetup.com/san-juan-bitdevs/', external: true}
